services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    # volumes:
      # - ./backend:/app
      # - ./backend/entrypoint.sh:/app/entrypoint.sh
    # entrypoint: backend/entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: brewit_user
      POSTGRES_PASSWORD: heineken2
      POSTGRES_DB: brewit_db
    ports:
      - 5432
      # - 5200:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: app
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data: