# Generated by Django 5.1.3 on 2024-12-02 00:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBrewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract_phone_number', models.CharField(max_length=30)),
                ('contract_email', models.EmailField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('nip', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='NIP number must be a string of 10 digits.', regex='^\\d{10}$')])),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractBrewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract_phone_number', models.CharField(max_length=30)),
                ('contract_email', models.EmailField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('BT', 'Tank warzelny'), ('FT', 'Pojemnik fermentacyjny'), ('AC', 'Kocioł do leżakowania'), ('BE', 'Urządzenie do rozlewania')], max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('temperature_min', models.IntegerField(null=True)),
                ('temperature_max', models.IntegerField(null=True)),
                ('sour_beers', models.BooleanField()),
                ('carbonation', models.CharField(max_length=100)),
                ('supported_containers', models.CharField(blank=True, max_length=255, null=True)),
                ('commercial_brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commercialbrewery')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_brewery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.commercialbrewery')),
                ('contract_brewery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contractbrewery')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_time', models.IntegerField(null=True)),
                ('full_volume', models.IntegerField(null=True)),
                ('contract_brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contractbrewery')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'Nowe'), ('C', 'Aktualne'), ('P', 'Przeszłe'), ('R', 'Odrzucone')], default='N', max_length=50)),
                ('beer_type', models.CharField(max_length=100)),
                ('beer_volume', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rate', models.CharField(blank=True, max_length=1, null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('contract_brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contractbrewery')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('BT', 'Tank warzelny'), ('FT', 'Pojemnik fermentacyjny'), ('AC', 'Kocioł do leżakowania'), ('BE', 'Urządzenie do rozlewania')], max_length=50)),
                ('time', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stage')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('F', 'Wolne'), ('R', 'Zarezerwowane'), ('H', 'Zajęte'), ('U', 'Niedostępne')], default='F', max_length=50)),
                ('slot_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
            ],
        ),
    ]
