# Generated by Django 5.1.3 on 2024-12-03 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('commercial_brewery__isnull', False), ('contract_brewery__isnull', False), _negated=True), name='brewery_arc'),
        ),
    ]
