# Generated by Django 5.1.3 on 2024-12-03 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_commercialbrewery_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbrewery',
            name='nip',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NIP number must be a string of 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
