# Generated by Django 5.1.3 on 2024-12-03 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_brewery_arc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commercial_brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.commercialbrewery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contract_brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contractbrewery'),
        ),
    ]
