# Generated by Django 5.1.3 on 2024-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_commercial_brewery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbrewery',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contractbrewery',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
