# Generated by Django 5.1.3 on 2024-12-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timeslot_timeslots_timestamps_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
    ]
