# Generated by Django 5.1.3 on 2024-12-08 14:06

import django_measurement.models
import measurement.measures.temperature
import measurement.measures.time
import measurement.measures.volume
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_timeslot_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='capacity',
            field=django_measurement.models.MeasurementField(blank=True, default=0, measurement=measurement.measures.volume.Volume),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='carbonation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='sour_beers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='supported_containers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature_max',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.temperature.Temperature, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature_min',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.temperature.Temperature, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='beer_volume',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume),
        ),
        migrations.AlterField(
            model_name='order',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='full_time',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.time.Time),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='full_volume',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='time',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.time.Time),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('D', 'Dzień'), ('H', 'Godzina')], max_length=50),
        ),
    ]
