# Generated by Django 5.1.3 on 2024-12-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_device_capacity_alter_device_carbonation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='full_time',
        ),
    ]
