# Generated by Django 5.1.4 on 2025-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timeslot_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
