# Generated by Django 5.1.4 on 2025-01-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_device_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbrewery',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractbrewery',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
