name: CI For Django App

on:
  push:
    branches:
      - main
      - backend-configure-tests
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: cp example.env .env

      - name: Build and run services
        run: docker compose up --build --detach

      - name: Run tests
        run: docker compose exec backend pytest --cov=core --cov-report=xml:/coverage.xml

      # i could add some formatting/linting actions here

      - name: Extract coverage report from container
        run: |
          container_name=$(docker compose ps -q backend)
          docker cp $container_name:/coverage.xml ./coverage.xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Shut down services
        if: always()
        run: docker compose down
