name: CI for Full Stack App

on:
  push:
    branches:
      - front-dev
  pull_request:
    branches:
      - front-dev

jobs:
  stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: cp example.env .env

      - name: Build and start Docker containers (frontend & backend)
        run: docker compose up --build --detach

      - name: Run backend tests
        run: docker compose exec backend pytest --cov=core --cov-report=xml:/coverage.xml

      - name: Extract coverage report from container
        run: |
          container_name=$(docker compose ps -q backend)
          docker cp $container_name:/coverage.xml ./coverage.xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Wait for frontend to be ready
        run: |
          sleep 15

      - name: Run health check for frontend
        run: |
          curl -f http://localhost:3000 || exit 1

      - name: Run tests in frontend container
        run: |
          docker compose exec frontend npm test

      - name: Stop Docker containers (frontend & backend)
        run: docker compose down
